%YAML:1.0
---
intrinsic_file: "../config/752/intrinsic.yml"
image_points_dir: "../config/752/"
stitch_file: "../config/752/stitch.yml"
left_right_to_front_distance: 1.4880000352859497e+00
car_y: 5.56
viewrange: 12.
pix_dis: 1.9999999552965164e-02
