%YAML:1.0
---
intrinsic_file: "../config/051/intrinsic.yml"
image_points_dir: "../config/051/"
stitch_file: "../config/051/stitch.yml"
left_right_to_front_distance: 1.517
car_y: 5.424
car_x: 2.205
viewrange: 12.
pix_dis: 1.9999999552965164e-02
